### PR TITLE
Chapter 17, chapter 18

### PR DESCRIPTION
**Pull request by liliamyhaliuk**
Hello!
I've done chapters 17 and chapters 18 from the book  Think Python.
Please, check when you have time. Thank you!

### CODE REVIEW

**Review by auraz — CHANGES_REQUESTED** [review]
Please add tests

**Review by auraz — COMMENTED** [review]
Good job with the unittests! 
Did they help you to make the program more clear and stable?

**Comment by liliamyhaliuk** [comment]
Hi!
Yeah, unit tests have helped me a lot with checking my program for weak spots and making it more stable. Thank you!

**Comment by liliamyhaliuk** [comment]
Hi! I've added also a complete version of Exercise 18.12.3 ( I had to do the function that counts the probability of each classification in 1 million hands).
Also, I've added Chapter 19. There is only one exercise there.

**Review by auraz — APPROVED** [review]

**Pull request merged**
